name: First Workflow

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the workflow

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Message
        run: echo "Hello, GitHub Actions! This is triggered by a push.Navdeep"
      
      - name: Success Message
        if: success() # Executes only if the previous steps were successful
        run: echo "Workflow completed successfully!"
